### PR TITLE
Add Xtransformer experiments

### PR DESCRIPTION
**Pull request by nsorros**
## Description

Related to #120 #121 #124 #125 

## Checklist

- [x] Linked to Notion or GitHub issue
- [ ] Added tests
- [ ] Updated README
- [ ] DVC up to date

## Release checklist

- [ ] DVC repro up to date
- [ ] Models synced in S3
- [ ] Version updated
- [ ] CHANGELOG.md updated
- [ ] Model and package version aligned

To release:

* `make build`
* `make deploy`

### CODE REVIEW

**Comment by nsorros** [comment]
Also opening this for review. Note that this is the skeleton for running XTransformers experiments. I have not tested it fully works as it would require running on multiple GPUs but it should not be far from working. I think it would be good to incorporate into the codebase.

**Comment by aCampello** [comment]
Is this superseded by the bertmesh model?

**Comment by nsorros** [comment]
> Is this superseded by the bertmesh model?

Yes, this PR does not add the experiments but more the code that is needed to run them just for completeness. I have not tested it works but it should not be far. We could possibly do as part of the experiments towards the publication as Transformers is a baseline we might want to compare with.

**Comment by nsorros** [comment]
Closing as unlikely to go back to this. But it will remain in closed PR if anyone wants to pick this up

**Pull request closed without merging**
