### PR TITLE
Feature split science dvc pipeline

### PR DESCRIPTION
**Pull request by aCampello**
## Description

Decouples science pipeline from production (xlinear) pipeline.

Dvc repro is still not up-to-date, as we'll do it after we finish all chunks of work.

## Checklist

- [ ] Linked to Notion or GitHub issue
- [ ] Added tests
- [ ] Updated README
- [ ] DVC up to date

## Release checklist

- [ ] DVC repro up to date
- [ ] Models synced in S3
- [ ] Version updated
- [ ] CHANGELOG.md updated
- [ ] Model and package version aligned

To release:

* `make build`
* `make deploy`

### CODE REVIEW

**Comment by aCampello** [comment]
Forgot to draft, but this is pretty much a draft

**Comment by ArneRobben** [comment]
Looks good. I can see the science bit in the original `dvc.yaml` and `parameters.yaml` is now separated in it's own `pipelines/science`

**Comment by ArneRobben** [comment]
my `pip install -r requirements.txt` really doesn't like the last line in the requirements: `git+https://github.com/nsorros/shap.git@dev`, do we need this?

**Review by ArneRobben — APPROVED** [review]

**Comment by aCampello** [comment]
> my `pip install -r requirements.txt` really doesn't like the last line in the requirements: `git+https://github.com/nsorros/shap.git@dev`, do we need this?

Yep, it's currently needed because of the experimental code that does explanations require a fork of Shap. When #223 is complete this won't be needed for xlinear.

**Pull request merged**
