### PR TITLE
Decouple prod code

### PR DESCRIPTION
**Pull request by aCampello**
## Checklist

- [ ] Linked to Notion or GitHub issue
- [ ] Added tests
- [ ] Updated README
- [ ] DVC up to date

## Release checklist

- [ ] DVC repro up to date
- [ ] Models synced in S3
- [ ] Version updated
- [ ] CHANGELOG.md updated
- [ ] Model and package version aligned

To release:

* `make build`
* `make deploy`

### CODE REVIEW

**Comment by ArneRobben** [comment]
I need a little time to test this out. Will review on Monday

**Comment by aCampello** [comment]
> I need a little time to test this out. Will review on Monday

This is not quite ready yet.

**Comment by ArneRobben** [comment]
Notebook is working fine: `{'threshold': '0.50', 'precision': '0.74', 'recall': '0.41', 'f1': '0.53'}`, I had to use r4.16xlarge rather than r4.xlarge to make it run

**Comment by ArneRobben** [comment]
`dvc repro dvc.yaml` isn't working atm:

```
(venv) ubuntu@ip-10-60-48-87:/data/grants_tagger$ dvc repro dvc.yaml
'data/raw/allMeSH_2021.json.dvc' didn't change, skipping              
Running stage 'preprocess_bioasq_mesh':
> grants_tagger preprocess bioasq-mesh data/raw/allMeSH_2021.json data/processed/train_mesh2021.jsonl models/xlinear/label_binarizer.pkl --test-split 0.01 --test-output-path data/processed/test_mesh2021.jsonl
2022-09-20 14:18:52.577314: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-09-20 14:18:52.577394: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/data/grants_tagger/venv/lib/python3.8/site-packages/tensorflow_addons/utils/ensure_tf_install.py:53: UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.7.0 and strictly below 2.10.0 (nightly versions are not supported). 
 The versions of TensorFlow you are currently using is 2.4.0 and is not supported. 
Some things might work, some things might not.
If you were to encounter a bug, do not file an issue.
If you want to make sure you're using a tested and supported configuration, either change the TensorFlow version or the TensorFlow Addons's version. 
You can find the compatibility matrix in TensorFlow Addon's readme:
https://github.com/tensorflow/addons
  warnings.warn(
/data/grants_tagger/venv/lib/python3.8/site-packages/gensim/similarities/__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)
2022-09-20 14:18:59.290735: I tensorflow/core/profiler/lib/profiler_session.cc:136] Profiler session initializing.
2022-09-20 14:18:59.290797: I tensorflow/core/profiler/lib/profiler_session.cc:155] Profiler session started.
2022-09-20 14:18:59.292944: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-09-20 14:18:59.293047: I tensorflow/core/profiler/lib/profiler_session.cc:172] Profiler session tear down.
2022-09-20 14:19:00 grants_tagger.cli WARNING: Sagemaker missing so training with sagemaker not working.
2022-09-20 14:19:00 grants_tagger.scispacy_meshtagger WARNING: SciSpacy missing. SciSpacyMeshTagger is not working
2022-09-20 14:19:00 grants_tagger.explain WARNING: shap missing. explain will not work
Traceback (most recent call last):
  File "/data/grants_tagger/venv/bin/grants_tagger", line 8, in <module>
    sys.exit(app())
  File "/data/grants_tagger/venv/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/data/grants_tagger/venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/data/grants_tagger/venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/data/grants_tagger/venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/grants_tagger/venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/grants_tagger/venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/grants_tagger/venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/data/grants_tagger/venv/lib/python3.8/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/data/grants_tagger/venv/lib/python3.8/site-packages/grants_tagger/preprocess_mesh.py", line 118, in preprocess_mesh_cli
    with open(params_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/grants_tagger/venv/lib/python3.8/site-packages/grants_tagger/../params.yaml'
ERROR: failed to reproduce 'preprocess_bioasq_mesh': failed to run: grants_tagger preprocess bioasq-mesh data/raw/allMeSH_2021.json data/processed/train_mesh2021.jsonl models/xlinear/label_binarizer.pkl --test-split 0.01 --test-output-path data/processed/test_mesh2021.jsonl, exited with 1
```

**Comment by ArneRobben** [comment]
To conclude this PR: both the notebook and `dvc repro dvc.yaml` work for me!

**Comment by aCampello** [comment]
excellent!

**Comment by aCampello** [comment]
I can't review it because I'm the author, so it's up to you to approve.

**Review by ArneRobben — APPROVED** [review]
I can run both the jupyter notebook and the dvc repro. Good to merge! I will test the docker build as well

**Pull request merged**
